# Generated by Django 4.0.6 on 2022-07-30 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_point'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Counter',
        ),
    ]
